name: Security audit

on:
  # TODO re-enable once project is set up properly
  #push:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  audit-check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Run security audit
        # Note: the action below is a temporary fork of rustsec/audit-check; it could be
        # replaced if, at some point, rustsec/audit-check is updated to use Node 20.
        uses: clechasseur/rustsec-audit-check@b5ade62a8d38826bb50ca4b8b9bc2a8a97f0d44d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
